# Generated by Django 3.0.5 on 2020-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
