# Generated by Django 3.0.5 on 2020-04-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncreditsale',
            name='receipt',
            field=models.ImageField(null=True, upload_to='sales/images'),
        ),
    ]
